name: Daily Digest Generator 📰

on:
  # 1. Schedule the script to run daily at 9:00 AM UTC
  schedule:
    # Use crontab format: minute hour day_of_month month day_of_week
    # '0 9 * * *' runs at 9:00 UTC 
    - cron: '0 9 * * *' 
  
  # 2. Allows manual running from the GitHub Actions tab
  workflow_dispatch: 

jobs:
  build:
    # Use a standard Linux runner environment
    runs-on: ubuntu-latest

    steps:
      # Step A: Get a copy of your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step B: Set up the correct Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step C: Install the required libraries (requests, python-dotenv)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      # Step D: Execute your main.py script
      # The env section injects your secrets for the script to use via os.getenv()
      - name: Run Python Script to Generate Digest
        run: python main.py
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS.API_KEY }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}

      # Step E: Commit the newly created index.html file back to the repo
      - name: Commit and Push new index.html
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Daily Digest index.html ☀️
          file_pattern: index.html